In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import metrics

In [2]:
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
dataset = pd.read_csv('../data/Iris.csv', names=names, header=None)
dataset

sepal-length  sepal-width  petal-length  petal-width           Class
1             5.1          3.5           1.4          0.2     Iris-setosa
2             4.9          3.0           1.4          0.2     Iris-setosa
3             4.7          3.2           1.3          0.2     Iris-setosa
4             4.6          3.1           1.5          0.2     Iris-setosa
5             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
146           6.7          3.0           5.2          2.3  Iris-virginica
147           6.3          2.5           5.0          1.9  Iris-virginica
148           6.5          3.0           5.2          2.0  Iris-virginica
149           6.2          3.4           5.4          2.3  Iris-virginica
150           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,4].values
print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(120, 4) (30, 4) (120,) (30,)


In [6]:
from sklearn.preprocessing import StandardScaler
s = StandardScaler()

X_train = s.fit_transform(X_train)
X_test = s.fit_transform(X_test)
print(X_train)
print(X_test)

[[-1.23078211e-01 -3.52930690e-01  3.03316319e-01  1.95165773e-01]
 [-8.49441423e-01 -1.24454506e+00 -3.66584754e-01 -6.65090066e-02]
 [-1.23078211e-01 -1.02164147e+00 -8.74593068e-02 -1.97346397e-01]
 [ 4.82224466e-01 -3.52930690e-01  3.59141409e-01  1.95165773e-01]
 [-2.44138746e-01 -5.75834283e-01  6.94091945e-01  1.11102750e+00]
 [-7.28380888e-01  2.32191243e+00 -1.20396110e+00 -1.37488291e+00]
 [-1.23078211e-01 -1.30027096e-01  3.03316319e-01  6.43283834e-02]
 [ 2.40103395e-01 -1.91325584e+00  7.49917035e-01  4.56840554e-01]
 [-1.09156249e+00  9.28764973e-02 -1.20396110e+00 -1.37488291e+00]
 [-1.21262303e+00  7.61587278e-01 -1.14813601e+00 -1.24404552e+00]
 [ 1.20858768e+00 -1.30027096e-01  1.02904248e+00  1.24186489e+00]
 [-1.23078211e-01  2.99062321e+00 -1.20396110e+00 -9.82370737e-01]
 [ 1.19042860e-01  3.15780091e-01  6.38266856e-01  8.49352724e-01]
 [-9.70501958e-01  3.15780091e-01 -1.37143636e+00 -1.24404552e+00]
 [-8.49441423e-01  7.61587278e-01 -1.20396110e+00 -1.24404552e

In [7]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 50)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=50)

In [8]:
from sklearn.metrics import accuracy_score
y_pred = knn.predict(X_test)
print(f"정확도: {accuracy_score(y_test, y_pred)}")

정확도: 0.8


In [9]:
import numpy as np

k = 10
acc_array = np.zeros(k)
for k in np.arange(1,k+1,1):
    classifier = KNeighborsClassifier(n_neighbors=k).fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    acc = metrics.accuracy_score(y_test, y_pred)
    acc_array[k-1]=acc

max_acc = np.amax(acc_array)
acc_list = list(acc_array)
k = acc_list.index(max_acc)
print(f"정확도 {max_acc} 으로 최적의 k는 {k+1} 입니다.")

정확도 0.8666666666666667 으로 최적의 k는 5 입니다.


In [ ]:
# %pip install tensorflow

In [11]:
from sklearn import svm
from sklearn import metrics
from sklearn import datasets
from sklearn import model_selection

In [13]:
import tensorflow as tf
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

In [15]:
iris = datasets.load_iris()

x_train, x_test, y_train, y_test = model_selection.train_test_split(iris.data, iris.target, test_size=0.6, random_state=42)

print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(60, 4) (90, 4) (60,) (90,)


In [16]:
svm = svm.SVC(kernel='linear', C=1.0, gamma=0.5)
svm.fit(x_train, y_train)
predictions = svm.predict(x_test)
score = metrics.accuracy_score(y_test, predictions)
print("정확도: {0:f}".format(score))

정확도: 0.988889
