In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [2]:
torch.manual_seed(1)
x_data = torch.FloatTensor([[1],[2],[3],[4],[5]])
y_data = torch.FloatTensor([[3],[5],[7],[9],[11]])

In [3]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(1,1)

    def forward(self, x):
        return self.linear(x)

In [4]:
# 모델 만들기
model = LinearRegressionModel()
print(model)

optimizer = optim.SGD(model.parameters(), lr=0.01)

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)


In [5]:
# 수행
epochs = 2001

for epoch in range(epochs):
    y = model(x_data)
    cost = F.mse_loss(y, x_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 == 0:
        print(f"epoch: {epoch}, cost: {cost.item()}, mocdel: {model.parameters()}")

epoch: 0, cost: 4.063195705413818, mocdel: <generator object Module.parameters at 0x0000025F868718C0>
epoch: 100, cost: 0.007522144820541143, mocdel: <generator object Module.parameters at 0x0000025FF2B9C900>
epoch: 200, cost: 0.003821000922471285, mocdel: <generator object Module.parameters at 0x0000025FF2B9C900>
epoch: 300, cost: 0.001940945745445788, mocdel: <generator object Module.parameters at 0x0000025FF2B9C900>
epoch: 400, cost: 0.000985942198894918, mocdel: <generator object Module.parameters at 0x0000025FF2B9C900>
epoch: 500, cost: 0.0005008282023482025, mocdel: <generator object Module.parameters at 0x0000025FF2B9C900>
epoch: 600, cost: 0.0002544031012803316, mocdel: <generator object Module.parameters at 0x0000025FF2B9C900>
epoch: 700, cost: 0.00012923004396725446, mocdel: <generator object Module.parameters at 0x0000025FF2B9C900>
epoch: 800, cost: 6.564263458130881e-05, mocdel: <generator object Module.parameters at 0x0000025FF2B9C900>
epoch: 900, cost: 3.334394205012359e-

In [6]:
predict = model(torch.FloatTensor([[7],[8]]))
print(predict)

tensor([[7.0003],
        [8.0004]], grad_fn=<AddmmBackward0>)


In [13]:
import pandas as pd
import torch

df = pd.read_csv('../data/data-01-test-score.csv')
x_data = df.values[:,:-1]           # 모든 행의 마지막 열앞까지
t_data = df.values[:,-1]            # 모든 행의 마지막 열만
print(x_data.shape)
print(t_data.shape)

t_data = t_data.reshape(-1, 1)
print(t_data.shape)

# 타입 확인
print(type(x_data), type(t_data))

# 텐서플로우로 바꿔주기
x_data1 = torch.from_numpy(x_data).float()
t_data1 = torch.from_numpy(t_data).float()
print(type(x_data1), type(t_data1))     # 훈련데이터 생성완료

indim = x_data1.size(1)
print(indim)

(24, 3)
(24,)
(24, 1)
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
<class 'torch.Tensor'> <class 'torch.Tensor'>
3


# 클래스 생성

In [8]:
class MultiLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(indim,1)
    
    # init, forward는 마음대로 짓는게 아니라 정해져있는 이름이다
    def forward(self,x):
        return self.linear(x)

# 모델 생성

In [9]:
model = MultiLinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr=1e-6)      # 1e-6 : 10의 마이너스 6승이라는 뜻

In [19]:
epochs = 200001
for epoch in range(epochs):
    y = model(x_data1)
    cost = F.mse_loss(y, t_data1)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100==0:
        print(epoch, cost.item(), list(model.parameters()))

0 6.383651256561279 [Parameter containing:
tensor([[0.3693, 0.5365, 1.1045]], requires_grad=True), Parameter containing:
tensor([0.3445], requires_grad=True)]
100 6.383577823638916 [Parameter containing:
tensor([[0.3692, 0.5365, 1.1045]], requires_grad=True), Parameter containing:
tensor([0.3445], requires_grad=True)]
200 6.38351583480835 [Parameter containing:
tensor([[0.3692, 0.5365, 1.1046]], requires_grad=True), Parameter containing:
tensor([0.3444], requires_grad=True)]
300 6.383452892303467 [Parameter containing:
tensor([[0.3691, 0.5365, 1.1046]], requires_grad=True), Parameter containing:
tensor([0.3444], requires_grad=True)]
400 6.383373260498047 [Parameter containing:
tensor([[0.3691, 0.5365, 1.1047]], requires_grad=True), Parameter containing:
tensor([0.3444], requires_grad=True)]
500 6.3833088874816895 [Parameter containing:
tensor([[0.3690, 0.5365, 1.1048]], requires_grad=True), Parameter containing:
tensor([0.3444], requires_grad=True)]
600 6.38323450088501 [Parameter cont

# 생성된 모델로 예측하기

In [20]:
x = torch.FloatTensor([[75,85,90],[90,85,75]])
model(x)

tensor([[173.2812],
        [161.7227]], grad_fn=<AddmmBackward0>)