# 머신러닝 수식

In [1]:
# 함수 생성
def my_fun1(x):
    return x**2

In [2]:
# 미분함수
def numerical_derivative(f, x):
    delta_x=1e-4

    return (f(x+delta_x)-f(x-delta_x))/(2*delta_x)

In [3]:
result=numerical_derivative(my_fun1, 3)
print(result)

6.000000000012662


In [4]:
def my_func2(x):
    return 2*x**2+3*x+1

In [5]:
result2=numerical_derivative(my_func2, 2)
print(result2)

11.00000000000989


## 수치미분 - 다변수

In [11]:
import numpy as np

def numerical_derivative2(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)
    print('x:',x)
    print('grad:',grad)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx=it.multi_index
        print('idx:',idx, 'x[idx]:', x[idx])
        tmp_val=x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x)
        x[idx]=float(tmp_val)-delta_x
        fx2=f(x)
        grad[idx]=(fx1-fx2)/(2*delta_x)
        print('grad[idx]:',grad[idx])
        print('grad:',grad)

        x[idx]=tmp_val
        it.iternext()

    return grad

In [7]:
def func3(input):
    x=input[0]
    y=input[1]
    return (2*x + 3*x*y + np.power(y, 3))

In [12]:
numerical_derivative2(func3, np.array([1.0,2.0]))

x: [1. 2.]
grad: [0. 0.]
idx: (0,) x[idx]: 1.0
grad[idx]: 7.999999999990237
grad: [8. 0.]
idx: (1,) x[idx]: 2.0
grad[idx]: 15.000000010019221
grad: [ 8.         15.00000001]


array([ 8.        , 15.00000001])

In [15]:
numerical_derivative2(my_fun1, np.array([3.0]))

x: [3.]
grad: [0.]
idx: (0,) x[idx]: 3.0
grad[idx]: 6.000000000012662
grad: [6.]


C:\Users\COM\AppData\Local\Temp\ipykernel_18428\2504724563.py:19: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  grad[idx]=(fx1-fx2)/(2*delta_x)


array([6.])

In [21]:
arr1=np.array([[1.0, 2.0],[3.0, 4.0]])
print(arr1)

[[1. 2.]
 [3. 4.]]


In [24]:
def func4(input):
    w=input[0][0]
    x=input[0][1]
    y=input[1][0]
    z=input[1][1]

    return (w*x + w*y*z + 3*2 + z*np.power(y,2))

In [25]:
numerical_derivative2(func4, arr1)

x: [[0.9999 2.    ]
 [3.     4.    ]]
grad: [[0. 0.]
 [0. 0.]]
idx: (0, 0) x[idx]: 0.9999
grad[idx]: 14.000000000002899
grad: [[14.  0.]
 [ 0.  0.]]
idx: (0, 1) x[idx]: 2.0
grad[idx]: 0.9998999999893954
grad: [[14.      0.9999]
 [ 0.      0.    ]]
idx: (1, 0) x[idx]: 3.0
grad[idx]: 27.999600000043756
grad: [[14.      0.9999]
 [27.9996  0.    ]]
idx: (1, 1) x[idx]: 4.0
grad[idx]: 11.999700000018265
grad: [[14.      0.9999]
 [27.9996 11.9997]]


array([[14.    ,  0.9999],
       [27.9996, 11.9997]])