# Basic

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [2]:
torch.manual_seed(1)
x_data=torch.FloatTensor([[1],[2],[3],[4],[5]])
t_data=torch.FloatTensor([[3],[5],[7],[9],[11]])

In [5]:
model1=nn.Linear(1,1)       # input_dim=1, output_dim=1 이라는 뜻(y=wx+b)
print(list(model1.parameters()))

[Parameter containing:
tensor([[-0.9414]], requires_grad=True), Parameter containing:
tensor([0.5997], requires_grad=True)]


In [6]:
optimizer=optim.SGD(model1.parameters(), lr=0.01)
epochs=20001

In [13]:
for epoch in range(epochs):
    h=model1(x_data)
    cost=F.mse_loss(h, t_data)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 == 0:
        print('epoch: ', epoch, 'cost: ', cost.item())

epoch:  0 cost:  7.644303245957218e-11
epoch:  100 cost:  7.644303245957218e-11
epoch:  200 cost:  7.644303245957218e-11
epoch:  300 cost:  7.644303245957218e-11
epoch:  400 cost:  7.644303245957218e-11
epoch:  500 cost:  7.644303245957218e-11
epoch:  600 cost:  7.644303245957218e-11
epoch:  700 cost:  7.644303245957218e-11
epoch:  800 cost:  7.644303245957218e-11
epoch:  900 cost:  7.644303245957218e-11
epoch:  1000 cost:  7.644303245957218e-11
epoch:  1100 cost:  7.644303245957218e-11
epoch:  1200 cost:  7.644303245957218e-11
epoch:  1300 cost:  7.644303245957218e-11
epoch:  1400 cost:  7.644303245957218e-11
epoch:  1500 cost:  7.644303245957218e-11
epoch:  1600 cost:  7.644303245957218e-11
epoch:  1700 cost:  7.644303245957218e-11
epoch:  1800 cost:  7.644303245957218e-11
epoch:  1900 cost:  7.644303245957218e-11
epoch:  2000 cost:  7.644303245957218e-11
epoch:  2100 cost:  7.644303245957218e-11
epoch:  2200 cost:  7.644303245957218e-11
epoch:  2300 cost:  7.644303245957218e-11
epoc

In [15]:
print(model1(torch.FloatTensor([[7],[8],[9]])))
print(list(model1.parameters()))

tensor([[15.0000],
        [17.0000],
        [19.0000]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[2.0000]], requires_grad=True), Parameter containing:
tensor([1.0000], requires_grad=True)]


In [19]:
import pandas as pd

df=pd.read_csv('../data/data-01-test-score.csv', header=None)
df

0   1    2    3
0   73  80   75  152
1   93  88   93  185
2   89  91   90  180
3   96  98  100  196
4   73  66   70  142
5   53  46   55  101
6   69  74   77  149
7   47  56   60  115
8   87  79   90  175
9   79  70   88  164
10  69  70   73  141
11  70  65   74  141
12  93  95   91  184
13  79  80   73  152
14  70  73   78  148
15  93  89   96  192
16  78  75   68  147
17  81  90   93  183
18  88  92   86  177
19  78  83   77  159
20  82  86   90  177
21  86  82   89  175
22  78  83   85  175
23  76  83   71  149
24  96  93   95  192