# Basic

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [48]:
x_data1=np.array([1,2,3,4,5]).reshape(5,1)
t_data1=np.array([3,5,7,9,11]).reshape(5,1)      # w = 2, b = 1 이 정답

print(x_data1)
print(t_data1)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [24]:
x_data2=np.array([[1,2],[2,3],[3,4],[4,5],[5,6]]).reshape(5,2)
t_data2=np.array([3,5,7,9,11]).reshape(5,1)      # w = 2, b = 1 이 정답

In [25]:
w2=np.random.rand(2,1)
b2=np.random.rand(1)
print(w2)
print(b2)

[[0.13460243]
 [0.49924354]]
[0.61405124]


In [17]:
w=np.random.rand(1,1)
b=np.random.rand(1)
print(w)
print(b)

[[0.87664719]]
[0.67927499]


In [32]:
# 손실함수 만들기
def loss_func1(x,t):
    y=np.dot(x,w2)+b2

    return (np.sum((t-y)**2))/(len(x))        # MSE

In [33]:
# 미분함수

def numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx=it.multi_index
        tmp_val=x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x)
        x[idx]=float(tmp_val)-delta_x
        fx2=f(x)
        grad[idx]=(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()

    return grad

In [46]:
# 새로운 값으로 예측하기
def predict(x):
    y=np.dot(x, w2)+b2
    return y

In [41]:
# 손실함수 값
cost_list=[]

# 러닝레이트 값
learing_rate=1e-4

f=lambda x:loss_func1(x_data2, t_data2)

print('Initial error value:',loss_func1(x_data2, t_data2))

for step in range(2000):
    w2-=learing_rate*numerical_derivative(f,w2)
    b2-=learing_rate*numerical_derivative(f,b2)

    if step % 100 == 0:
        print('step: ', step, 'error value: ', loss_func1(x_data2,t_data2), 'w: ', w2, 'b', b2)

Initial error value: 19.61431235606731
step:  0 error value:  19.38292426513062 w:  [[0.13753999]
 [0.50297813]] b [0.61484353]
step:  100 error value:  5.9628792684988055 w:  [[0.35846901]
 [0.78306046]] b [0.67364021]
step:  200 error value:  1.9010319134782616 w:  [[0.4808235]
 [0.936757 ]] b [0.7047859]
step:  300 error value:  0.6710874840685559 w:  [[0.54894882]
 [1.02093023]] b [0.72072558]
step:  400 error value:  0.2981179013043636 w:  [[0.58723939]
 [1.06686017]] b [0.72830524]
step:  500 error value:  0.1844870919358727 w:  [[0.60911457]
 [1.09175398]] b [0.73129083]
step:  600 error value:  0.1493427632992228 w:  [[0.6219564 ]
 [1.10507731]] b [0.73175397]
step:  700 error value:  0.137956304428939 w:  [[0.62982571]
 [1.11203721]] b [0.73083426]
step:  800 error value:  0.13376578288383684 w:  [[0.63495642]
 [1.11549807]] b [0.72915856]
step:  900 error value:  0.13175909465525296 w:  [[0.6385774 ]
 [1.11703558]] b [0.72707169]
step:  1000 error value:  0.13041934304877661 

In [47]:
# 예측값
predict(np.array([[6,7]]))
predict(np.array([[7,8]]))

array([[14.20855639]])