# Basic

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [22]:
# 재실행 후에도 동일한 결과가 나오도록 랜덤 시드를 설정
torch.manual_seed(1)

# 변수 선언
x_train=torch.FloatTensor([[1],[2],[3],[4],[5]])
y_train=torch.FloatTensor([[2],[4],[6],[8],[10]])

# 선언한 변수와 변수 형태 확인
print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])
torch.Size([5, 1])
tensor([[ 2.],
        [ 4.],
        [ 6.],
        [ 8.],
        [10.]])
torch.Size([5, 1])


In [24]:
w=torch.zeros(1, requires_grad=True)
print(w)
b=torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [5]:
# 가설 만들기
h=x_train*w+b
print(h)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [6]:
cost=torch.mean((h-y_train)**2)
print(cost)

tensor(44., grad_fn=<MeanBackward0>)


In [7]:
optimizer=optim.SGD([w, b], lr=0.01)

In [8]:
optimizer.zero_grad()

In [10]:
cost.backward()

In [11]:
optimizer.step()

In [35]:
epochs=20000
for epoch in range(epochs):
    h=x_train*w+b

    cost=torch.mean((h - y_train)**2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w:{:.3f} b:{:.3f} cost:{:.6f}'.format(
            epoch, epochs, w.item(), b.item(), cost.item()
        ))

Epoch    0/20000 w:2.000 b:0.006 cost:0.000036
Epoch  100/20000 w:2.000 b:0.001 cost:0.000001
Epoch  200/20000 w:2.000 b:0.000 cost:0.000000
Epoch  300/20000 w:2.000 b:0.000 cost:0.000000
Epoch  400/20000 w:2.000 b:0.000 cost:0.000000
Epoch  500/20000 w:2.000 b:0.000 cost:0.000000
Epoch  600/20000 w:2.000 b:0.000 cost:0.000000
Epoch  700/20000 w:2.000 b:0.000 cost:0.000000
Epoch  800/20000 w:2.000 b:0.000 cost:0.000000
Epoch  900/20000 w:2.000 b:0.000 cost:0.000000
Epoch 1000/20000 w:2.000 b:0.000 cost:0.000000
Epoch 1100/20000 w:2.000 b:0.000 cost:0.000000
Epoch 1200/20000 w:2.000 b:0.000 cost:0.000000
Epoch 1300/20000 w:2.000 b:0.000 cost:0.000000
Epoch 1400/20000 w:2.000 b:0.000 cost:0.000000
Epoch 1500/20000 w:2.000 b:0.000 cost:0.000000
Epoch 1600/20000 w:2.000 b:0.000 cost:0.000000
Epoch 1700/20000 w:2.000 b:0.000 cost:0.000000
Epoch 1800/20000 w:2.000 b:0.000 cost:0.000000
Epoch 1900/20000 w:2.000 b:0.000 cost:0.000000
Epoch 2000/20000 w:2.000 b:0.000 cost:0.000000
Epoch 2100/20

In [21]:
h=torch.FloatTensor([[7]])*w+b
print(h)

tensor([[0.]], grad_fn=<AddBackward0>)


In [31]:
# 데이터
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

# 모델 초기화
W = torch.zeros(1,requires_grad=True)
b = torch.zeros(1,requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W,b], lr=0.01)

nb_epochs = 2000

for epoch in range(nb_epochs+1):
    hypothesis = x_train * W + b

    cost = torch.mean((hypothesis - y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))


Epoch    0/2000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008

In [28]:
import torch
w = torch.tensor(2.0, requires_grad=True)
print(w)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    z = 2*w
    z.backward()
    print('수식을 w로 미분한 값 : {}'.format(w.grad))

tensor(2., requires_grad=True)
수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


In [33]:
import numpy as np

x_data1=np.array([1,2,3,4,5]).reshape(5,1)
t_data1=np.array([3,5,7,9,11]).reshape(5,1)      # w = 2, b = 1 이 정답

print(x_data1)
print(t_data1)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [34]:
x_data=torch.from_numpy(x_data1).float()
t_data=torch.from_numpy(t_data1).float()
print(x_data)
print(t_data)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])
tensor([[ 3.],
        [ 5.],
        [ 7.],
        [ 9.],
        [11.]])


# data 활용하기

In [50]:
import pandas as pd

df=pd.read_csv('../data/data-01-test-score.csv', header=None)
df

0   1    2    3
0   73  80   75  152
1   93  88   93  185
2   89  91   90  180
3   96  98  100  196
4   73  66   70  142
5   53  46   55  101
6   69  74   77  149
7   47  56   60  115
8   87  79   90  175
9   79  70   88  164
10  69  70   73  141
11  70  65   74  141
12  93  95   91  184
13  79  80   73  152
14  70  73   78  148
15  93  89   96  192
16  78  75   68  147
17  81  90   93  183
18  88  92   86  177
19  78  83   77  159
20  82  86   90  177
21  86  82   89  175
22  78  83   85  175
23  76  83   71  149
24  96  93   95  192

In [68]:
data=df.values
x_data=data[:,:3].reshape(-1, 3)
y_data=data[:,:-1].reshape(-1, 1)
print(x_data)
print(y_data)

[[ 73  80  75]
 [ 93  88  93]
 [ 89  91  90]
 [ 96  98 100]
 [ 73  66  70]
 [ 53  46  55]
 [ 69  74  77]
 [ 47  56  60]
 [ 87  79  90]
 [ 79  70  88]
 [ 69  70  73]
 [ 70  65  74]
 [ 93  95  91]
 [ 79  80  73]
 [ 70  73  78]
 [ 93  89  96]
 [ 78  75  68]
 [ 81  90  93]
 [ 88  92  86]
 [ 78  83  77]
 [ 82  86  90]
 [ 86  82  89]
 [ 78  83  85]
 [ 76  83  71]
 [ 96  93  95]]
[[ 73]
 [ 80]
 [ 75]
 [ 93]
 [ 88]
 [ 93]
 [ 89]
 [ 91]
 [ 90]
 [ 96]
 [ 98]
 [100]
 [ 73]
 [ 66]
 [ 70]
 [ 53]
 [ 46]
 [ 55]
 [ 69]
 [ 74]
 [ 77]
 [ 47]
 [ 56]
 [ 60]
 [ 87]
 [ 79]
 [ 90]
 [ 79]
 [ 70]
 [ 88]
 [ 69]
 [ 70]
 [ 73]
 [ 70]
 [ 65]
 [ 74]
 [ 93]
 [ 95]
 [ 91]
 [ 79]
 [ 80]
 [ 73]
 [ 70]
 [ 73]
 [ 78]
 [ 93]
 [ 89]
 [ 96]
 [ 78]
 [ 75]
 [ 68]
 [ 81]
 [ 90]
 [ 93]
 [ 88]
 [ 92]
 [ 86]
 [ 78]
 [ 83]
 [ 77]
 [ 82]
 [ 86]
 [ 90]
 [ 86]
 [ 82]
 [ 89]
 [ 78]
 [ 83]
 [ 85]
 [ 76]
 [ 83]
 [ 71]
 [ 96]
 [ 93]
 [ 95]]


In [69]:
x_train=torch.from_numpy(x_data).float()
y_train=torch.from_numpy(y_data).float()

print(x_train)
print(y_train)

tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.],
        [ 53.,  46.,  55.],
        [ 69.,  74.,  77.],
        [ 47.,  56.,  60.],
        [ 87.,  79.,  90.],
        [ 79.,  70.,  88.],
        [ 69.,  70.,  73.],
        [ 70.,  65.,  74.],
        [ 93.,  95.,  91.],
        [ 79.,  80.,  73.],
        [ 70.,  73.,  78.],
        [ 93.,  89.,  96.],
        [ 78.,  75.,  68.],
        [ 81.,  90.,  93.],
        [ 88.,  92.,  86.],
        [ 78.,  83.,  77.],
        [ 82.,  86.,  90.],
        [ 86.,  82.,  89.],
        [ 78.,  83.,  85.],
        [ 76.,  83.,  71.],
        [ 96.,  93.,  95.]])
tensor([[ 73.],
        [ 80.],
        [ 75.],
        [ 93.],
        [ 88.],
        [ 93.],
        [ 89.],
        [ 91.],
        [ 90.],
        [ 96.],
        [ 98.],
        [100.],
        [ 73.],
        [ 66.],
        [ 70.],
        [ 53.],
        [ 46.],
        [ 55.],
        [ 6

In [70]:
W=torch.zeros((3,1), requires_grad=True)
b=torch.zeros((1), requires_grad=True)
print(W)
print(b)

tensor([[0.],
        [0.],
        [0.]], requires_grad=True)
tensor([0.], requires_grad=True)


In [71]:
cost_list=[]
optimizer=optim.SGD([W,b], lr=1e-6)
epochs=30001

In [72]:
for epoch in range(epochs):
    y=x_train.matmul(W)+b
    cost=torch.mean((y-y_train)**2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    cost_list.append([epoch, cost])

    if epoch%100 == 0:
        print('epoch: ', epoch, 'cost: ', cost.item(), "W: ", W, "b: ", b.item())

RuntimeError: The size of tensor a (25) must match the size of tensor b (75) at non-singleton dimension 0

In [74]:
def predict(x):
    return x.matmul(W)+b

In [75]:
new_data=torch.FloatTensor([[65,68,70], [100,95,90],[90,95,100]])
predict(new_data)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)